import os
from sys import argv
 
def latinizator(letter, dic):
    for i, j in dic.items():
        letter = letter.replace(i, j)
    return letter
 
legend = {
' ':'_',
',':'',
'.':'_',
'«':'',
'»':'',
'(':'',
')':'',
'|':'',
'–':'',
'-':'',
'—':'',
'^':'',
'&':'',
'{':'',
'}':'',
'#':'',
'№':'',
'а':'a',
'б':'b',
'в':'v',
'г':'g',
'д':'d',
'е':'e',
'ё':'yo',
'ж':'zh',
'з':'z',
'и':'i',
'й':'y',
'к':'k',
'л':'l',
'м':'m',
'н':'n',
'о':'o',
'п':'p',
'р':'r',
'с':'s',
'т':'t',
'у':'u',
'ф':'f',
'х':'h',
'ц':'c',
'ч':'ch',
'ш':'sh',
'щ':'sh',
'ъ':'y',
'ы':'y',
'ь':"'",
'э':'e',
'ю':'yu',
'я':'ya',
'А':'a',
'Б':'b',
'В':'v',
'Г':'g',
'Д':'d',
'Е':'e',
'Ё':'yo',
'Ж':'zh',
'З':'z',
'И':'i',
'Й':'y',
'К':'k',
'Л':'l',
'М':'m',
'Н':'n',
'О':'o',
'П':'p',
'Р':'r',
'С':'s',
'Т':'t',
'У':'u',
'Ф':'f',
'Х':'h',
'Ц':'ts',
'Ч':'ch',
'Ш':'sh',
'Щ':'sh',
'Ъ':'y',
'Ы':'y',
'Ь':'',
'Э':'e',
'Ю':'yu',
'Я':'ya',
'A':'a',
'B':'b',
'C':'c',
'D':'d',
'E':'e',
'F':'f',
'G':'g',
'H':'h',
'I':'i',
'J':'j',
'K':'k',
'L':'l',
'M':'m',
'N':'n',
'O':'o',
'P':'p',
'Q':'q',
'R':'r',
'S':'s',
'T':'t',
'U':'u',
'V':'v',
'W':'w',
'X':'x',
'Y':'y',
'Z':'z',
'__':'_',
"'":'',
"’":'',
#'.'
'_mp3':'.mp3',
'_wav':'.wav',
'_ogg':'.ogg',
'_aiff':'.aiff',
'_aif':'.aif',
'_flac':'.flac',
'_dsd':'.dsd',
'_mqa':'.mqa',
'_wma':'.wma',
'_aac':'.aac',
'_m4a':'.m4a',
'_doc':'.doc',
'_docx':'.docx',
'_docm':'.docm',
'_dot':'.dot',
'_dotx':'.dotx',
'_dotm':'.dotm',
'_txt':'.txt',
'_txtn':'.txtn',
'_xlsx':'.xlsx',
'_xls':'.xls',
'_xslsm':'.xslsm',
'_xlt':'.xlt',
'_xltx':'.xltx',
'_xltm':'.xltm',
'_pdf':'.pdf',
'_pptx':'.pptx',
'_ppt':'.ppt',
'_ppsx':'.ppsx',
'_pps':'.pps',
'_ppsm':'.ppsm',
'_pptm':'.pptm',
'_potm':'.potm',
'_pot':'.pot',
'_dll':'.dll',
'_zip':'.zip',
'_7z':'.7z',
'_rar':'.rar',
'_pyd':'.pyd',
'_py':'.py',
'_exe':'.exe',
'_mp4':'.mp4',
'_mov':'.mov',
'_avi:':'.avi',
'_mkv:':'.mkv',
'_wmv:':'.wmv',
'_flv:':'.flv',
'_avchd:':'.avchd',
'_f4v:':'.f4v',
'_swf:':'.swf',
'_mpv:':'.mpv',
'_mpe:':'.mpe',
'_mp2:':'.mp2',
'_mpeg:':'.mpeg',
'_mpg:':'.mpg',
'_3gp:':'.3gp',
'_m4v:':'.m4v',
'_qt:':'.qt',
'_mxf:':'.mxf',
'_tga':'.tga',
'_jpg':'.jpg',
'_jpeg':'.jpeg',
'_heif':'.heif',
'_heic':'.heic',
'_png':'.png',
'_ico':'.ico',
'_gif':'.gif',
'_tif':'.tif',
'_tiff':'.tiff',
'_svg':'.svg',
'_jfif':'.jfif',
'_pct':'.pct',
'_pict':'.pict',
'_raw':'.raw',
'_jp2':'.jp2',
'_bmp':'.bmp',
}
 
for file_old in os.listdir('.'):
 
    file_new = latinizator(file_old, legend)
 
    #Uncomment to capitalize first letter of filename
    #file_new = file_new.capitalize()
 
    if '-p' in argv:
        if file_old == file_new:
            print ('{0: <30}'.format(file_old), 'will not be renamed' )
        else:
            print ('{0: <30}'.format(file_old), 'will be renamed to ', file_new )
    else:
        if file_old != file_new:
            print ('{0: <30}'.format(file_old), 'renamed to ', file_new )
            os.rename(file_old, file_new)
 
#lisakov
#softy_plug